import sys

if len(sys.argv) < 2: # si la date n'est pas renseigné alors...
    print(f"[*] - Merci d'entrer une date valide (ex: python3 {sys.argv[0]} jj/mm/aaaa)")
else:
    if not "/" in sys.argv[1]:
        print(f"[*] - Merci d'entrer une date dans un format valide tel que jj/mm/aaaa : 16/03/2004")
        sys.exit()

    jour = sys.argv[1].split("/")[0] # récupération du jour
    mois = sys.argv[1].split("/")[1] # récupération du mois
    annee = sys.argv[1].split("/")[2] # récupération de l'année

    noms_jours = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"] # liste des jours de la semaine
    code_mois = [0, 3 ,3 ,6 ,1 ,4 ,6 ,2 ,5 ,0 ,3 ,5] # code des mois

    j = int(jour) # jour
    m = int(mois) # mois
    a = int(annee)-1900 # année - 1900

    if(a % 400 == 0 or  (a % 4 == 0 and a % 100 != 0)): # vérification si l'année est bisextile ou non
        bisextile = 1 # année bisextile
    else:
        bisextile = 0 # année non bisextile

    xd = (j + code_mois[m-1] + (a+a//4) - int(m<=2) * bisextile) % 7 # calcul afin de trouver le jour

    if(bisextile == 1): # si l'année est bisextile alors ...
        if(mois == "01"): # si le mois = 01 (Janvier) alors...
            print(f"Né(e) le {jour} Janvier en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "02"): # si le mois = 02 (Février) alors...
            print(f"Né(e) le {jour} Février en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "03"): # si le mois = 03 (Mars) alors...
            print(f"Né(e) le {jour} Mars en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "04"): # si le mois = 04 (Avril) alors...
            print(f"Né(e) le {jour} Avril en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "05"): # si le mois = 05 (Mai) alors...
            print(f"Né(e) le {jour} Mai en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "06"): # si le mois = 06 (Juin) alors...
            print(f"Né(e) le {jour} Juin en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "07"): # si le mois = 07 (Juillet) alors...
            print(f"Né(e) le {jour} Juillet en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "08"): # si le mois = 08 (Août) alors...
            print(f"Né(e) le {jour} Août en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "09"): # si le mois = 09 (Septembre) alors...
            print(f"Né(e) le {jour} Septembre en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "10"): # si le mois = 10 (Octobre) alors...
            print(f"Né(e) le {jour} Octobre en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "11"): # si le mois = 11 (Novembre) alors...
            print(f"Né(e) le {jour} Novembre en {annee} un {noms_jours[xd]} durant une année bisextile")
        if(mois == "12"): # si le mois = 12 (Décembre) alors...
            print(f"Né(e) le {jour} Décembre en {annee} un {noms_jours[xd]} durant une année bisextile")

    elif(bisextile == 0): # si l'année n'est pas bisextile alors ...
        if(mois == "01"): # si le mois = 01 (Janvier) alors...
            print(f"Né(e) le {jour} Janvier en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "02"): # si le mois = 02 (Février) alors...
            print(f"Né(e) le {jour} Février en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "03"): # si le mois = 03 (Mars) alors...
            print(f"Né(e) le {jour} Mars en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "04"): # si le mois = 04 (Avril) alors...
            print(f"Né(e) le {jour} Avril en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "05"): # si le mois = 05 (Mai) alors...
            print(f"Né(e) le {jour} Mai en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "06"): # si le mois = 06 (Juin) alors...
            print(f"Né(e) le {jour} Juin en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "07"): # si le mois = 07 (Juillet) alors...
            print(f"Né(e) le {jour} Juillet en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "08"): # si le mois = 08 (Août) alors...
            print(f"Né(e) le {jour} Août en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "09"): # si le mois = 09 (Septembre) alors...
            print(f"Né(e) le {jour} Septembre en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "10"): # si le mois = 10 (Octobre) alors...
            print(f"Né(e) le {jour} Octobre en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "11"): # si le mois = 11 (Novembre) alors...
            print(f"Né(e) le {jour} Novembre en {annee} un {noms_jours[xd]} durant une année non bisextile")
        if(mois == "12"): # si le mois = 12 (Décembre) alors...
            print(f"Né(e) le {jour} Décembre en {annee} un {noms_jours[xd]} durant une année non bisextile")
